apiVersion: v1
kind: Secret
metadata:
  name: {{ include "locate360-service.fullname" . }}-secret
type: Opaque
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
