nameOverride: user-service
image:
  repository: harbor.company.internal/locate360/user-service
  tag: "1.0.0"
ingress:
  host: user-service.locate360.internal
vault:
  path: secret/data/locate360/user-service
